/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { EmployeeCreateNestedManyWithoutMinesInput } from "./EmployeeCreateNestedManyWithoutMinesInput";
import { Type } from "class-transformer";
import { EquipmentCreateNestedManyWithoutMinesInput } from "./EquipmentCreateNestedManyWithoutMinesInput";
import { MaterialCreateNestedManyWithoutMinesInput } from "./MaterialCreateNestedManyWithoutMinesInput";
import { ReportCreateNestedManyWithoutMinesInput } from "./ReportCreateNestedManyWithoutMinesInput";

@InputType()
class MineCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeCreateNestedManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => EmployeeCreateNestedManyWithoutMinesInput)
  @IsOptional()
  @Field(() => EmployeeCreateNestedManyWithoutMinesInput, {
    nullable: true,
  })
  employees?: EmployeeCreateNestedManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => EquipmentCreateNestedManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => EquipmentCreateNestedManyWithoutMinesInput)
  @IsOptional()
  @Field(() => EquipmentCreateNestedManyWithoutMinesInput, {
    nullable: true,
  })
  equipmentItems?: EquipmentCreateNestedManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => MaterialCreateNestedManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => MaterialCreateNestedManyWithoutMinesInput)
  @IsOptional()
  @Field(() => MaterialCreateNestedManyWithoutMinesInput, {
    nullable: true,
  })
  materials?: MaterialCreateNestedManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutMinesInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutMinesInput, {
    nullable: true,
  })
  reports?: ReportCreateNestedManyWithoutMinesInput;
}

export { MineCreateInput as MineCreateInput };
