/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { EmployeeUpdateManyWithoutMinesInput } from "./EmployeeUpdateManyWithoutMinesInput";
import { Type } from "class-transformer";
import { EquipmentUpdateManyWithoutMinesInput } from "./EquipmentUpdateManyWithoutMinesInput";
import { MaterialUpdateManyWithoutMinesInput } from "./MaterialUpdateManyWithoutMinesInput";
import { ReportUpdateManyWithoutMinesInput } from "./ReportUpdateManyWithoutMinesInput";

@InputType()
class MineUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeUpdateManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => EmployeeUpdateManyWithoutMinesInput)
  @IsOptional()
  @Field(() => EmployeeUpdateManyWithoutMinesInput, {
    nullable: true,
  })
  employees?: EmployeeUpdateManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => EquipmentUpdateManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => EquipmentUpdateManyWithoutMinesInput)
  @IsOptional()
  @Field(() => EquipmentUpdateManyWithoutMinesInput, {
    nullable: true,
  })
  equipmentItems?: EquipmentUpdateManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => MaterialUpdateManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => MaterialUpdateManyWithoutMinesInput)
  @IsOptional()
  @Field(() => MaterialUpdateManyWithoutMinesInput, {
    nullable: true,
  })
  materials?: MaterialUpdateManyWithoutMinesInput;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutMinesInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutMinesInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutMinesInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutMinesInput;
}

export { MineUpdateInput as MineUpdateInput };
