/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Equipment } from "./Equipment";
import { EquipmentCountArgs } from "./EquipmentCountArgs";
import { EquipmentFindManyArgs } from "./EquipmentFindManyArgs";
import { EquipmentFindUniqueArgs } from "./EquipmentFindUniqueArgs";
import { CreateEquipmentArgs } from "./CreateEquipmentArgs";
import { UpdateEquipmentArgs } from "./UpdateEquipmentArgs";
import { DeleteEquipmentArgs } from "./DeleteEquipmentArgs";
import { Mine } from "../../mine/base/Mine";
import { EquipmentService } from "../equipment.service";
@graphql.Resolver(() => Equipment)
export class EquipmentResolverBase {
  constructor(protected readonly service: EquipmentService) {}

  async _equipmentItemsMeta(
    @graphql.Args() args: EquipmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Equipment])
  async equipmentItems(
    @graphql.Args() args: EquipmentFindManyArgs
  ): Promise<Equipment[]> {
    return this.service.equipmentItems(args);
  }

  @graphql.Query(() => Equipment, { nullable: true })
  async equipment(
    @graphql.Args() args: EquipmentFindUniqueArgs
  ): Promise<Equipment | null> {
    const result = await this.service.equipment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Equipment)
  async createEquipment(
    @graphql.Args() args: CreateEquipmentArgs
  ): Promise<Equipment> {
    return await this.service.createEquipment({
      ...args,
      data: {
        ...args.data,

        mine: args.data.mine
          ? {
              connect: args.data.mine,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Equipment)
  async updateEquipment(
    @graphql.Args() args: UpdateEquipmentArgs
  ): Promise<Equipment | null> {
    try {
      return await this.service.updateEquipment({
        ...args,
        data: {
          ...args.data,

          mine: args.data.mine
            ? {
                connect: args.data.mine,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Equipment)
  async deleteEquipment(
    @graphql.Args() args: DeleteEquipmentArgs
  ): Promise<Equipment | null> {
    try {
      return await this.service.deleteEquipment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Mine, {
    nullable: true,
    name: "mine",
  })
  async getMine(@graphql.Parent() parent: Equipment): Promise<Mine | null> {
    const result = await this.service.getMine(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
